### ISSUE TITLE
Authorized Users must be able to manage appointments

### ISSUE THREAD

**Issue by mirsaalf** [mirsaalf/WebsiteProject#4]
Owner/Authorized User should have full CRUD functionality for web page

- [ ] Add Authorized User role
- [ ] Authorized User can create appointments and invoices (Client name/contact information/payment information/business or residential work)
- [ ] Authorized Users can Edit appointments
- [ ] Authorized Users can Delete (cancel) appointments 
- [ ] Only authorized users can edit/delete appointments and see client personal information
